### ISSUE TITLE
Request - Point Blank Sound

### ISSUE THREAD

**Issue by msheehan79** [libretro-mirrors/mame2003-plus-libretro#1]
Thanks for all the updates to this core! This isn't an issue, just a request/question. Would it be possible to look at what would be needed to backport sound for Point Blank into this core, if it could be done or are the changes too great? (and of course, if you are willing :))

**Comment by arcadez** [comment]
I cant do the above as the CPU which drives the sound for these games is not compatable with
this older core hence i wont be able to backport it.

**Comment by msheehan79** [comment]
No worries. Thanks for looking at least!

**Comment by arcadez** [comment]
Hey no problem i didn't have to look into it really as i've actually did this already for another 
project, it's just a pity this core wasn't MAME79 as then the sound core and the CPU would
have dropped in quite easy and bingo you'd have sound in Point blank and all the other games
in that driver.
